# These github actions will perform linting using pre-commit.
# yamllint disable rule:line-length
# spell-checker: disable
---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install talisman
        run: |
          sudo curl -sLo /usr/local/bin/talisman https://github.com/thoughtworks/talisman/releases/download/v1.31.0/talisman_linux_amd64
          sudo chmod 0755 /usr/local/bin/talisman
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.6'
          bundler-cache: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: pre-commit/action@v3.0.0
